OperacionesBasicas = function(a,b){
  print("Suma")
  print(a+b)
  print("Resta")
  print(paste(sprintf("%i - %i =",a,b),a-b))
  print(paste(sprintf("%i - %i =",b,a),b-a))
  print("Producto")
  print(a*b)
  print("Division Entera")
  print(paste(sprintf("%i : %i =",a,b),a%/%b))
  print(paste("con resto",a%%b))
  print("Division Entera")
  print(paste(sprintf("%i : %i =",b,a),b%/%a))
  print(paste("con resto",b%%a))
}
OperacionesBasicas(5,6)
OperacionesBasicas(6,5)
OperacionesBasicas(6,4)
