---
title: "Seccion9_Tema67_Graficos"
author: "Ricardo Marrero"
date: "10/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos con la función `plot`

 ```{r primer_plot, fig.cap= "Notas por alumnos", fig.align='center',echo=FALSE,}
alumnos = c(1:10)
notas = c(2,5,7,9,8,3,5,6,10,7)
plot(alumnos,notas)
plot(alumnos,notas, main = "Grafico con texto")
text(alumnos,notas, labels = c("S","A","N","E","N","S","A","A","E","N"), 
     pos = c(rep(3,times = 8),1,3))
```

```{r funcion_fibonacci, fig.cap= "Notas por alumnos", fig.align='center',echo=FALSE}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
fib
plot(fib, xlab = "n", ylab = expression(F[n]), main = "Sucesión de Fibonacci",
     pch = 19, col="powderblue")
```

```{r tipo de grafico, fig.cap= "Notas por alumnos", fig.align='center',echo=FALSE}
par(mfrow = c(3,2))
x = c(50:59)
y = c(2,9,25,3,100,77,62,54,19,40)
plot(x,y, pch = 23, cex = 2, col = "blue", type = "p")
plot(x,y, pch = 23, cex = 2, col = "blueviolet", type = "l")
plot(x,y, pch = 23, cex = 2, col = "gold", type = "b")
plot(x,y, pch = 23, cex = 2, col = "deeppink", type = "o")
plot(x,y, pch = 23, cex = 2, col = "springgreen", type = "h")
plot(x,y, pch = 23, cex = 2, col = "firebrick1", type = "s")
par(mfrow = c(1,1))
```

```{r agregar elementos, fig.cap= "Notas por alumnos", fig.align='center',echo=FALSE}
f <- function(x){
  x^2 -2*x + sqrt(abs(x))
}
plot(f, xlim = c(-3,3))
points(0,0, pch = 19)
points(-3:3, (-3:3)^2, col = "blue")
abline(2,3, lty = "dashed", col = "red")
abline(v = 2, lty = "dotted", col = "black")
abline(h = 5, lty = "dotdash", col = "gray")
```



